# Generated by Django 3.2.9 on 2021-11-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20211120_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='scene_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Сценическое имя исполнителя'),
        ),
    ]
