# Generated by Django 3.2.9 on 2021-11-20 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_artist_scene_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя исполнителя'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='scene_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='Сценическое имя исполнителя'),
            preserve_default=False,
        ),
    ]
